version: "3"

services:
  api:
    container_name: phpfpm
    build:
      context: ./Dockerfiles/php
    working_dir: /var/www
    volumes:
      - ./src/php:/var/www
    expose:
      - "9000"
  database:
    container_name: db
    image: mysql
    ports:
    - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "marinetraffic"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
  test_database:
    container_name: test_db
    image: mysql
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "marinetraffic"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
      MYSQL_TCP_PORT: 3307
#  frontend:
#    container_name: vue
#    image: node:latest
#    environment:
#      - NODE_OPTIONS=--openssl-legacy-provider
#      - NODE_ENV=development
#    working_dir: /home/node/app
#    expose:
#      - 8080
#    volumes:
#      - ./src/vue:/home/node/app
#    ports:
#      - "8080:8080"
#    command: bash -c "npm install -g @vue/cli && npm install && npm run serve"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/marinetraffic.conf:/etc/nginx/conf.d/default.conf
      - ./keys/ssl:/etc/ssl/certs
      - ./src/php:/var/www
    links:
      - api
